default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: autolizer_development

test:
  <<: *default
  database: autolizer_test

production:
  <<: *default
  database: autolizer_production
  # username: autolizer
  # password: <%= ENV['AUTOLIZER_DATABASE_PASSWORD'] %>
